config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index' 

  root 'welcome#index'

  resources :sessions

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "users#new"

  resources :users

  resources :comments


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def authorize
	  redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comment = Comment.all
	end	

	def new
		@comment = Comment.new
	end
	
	def create
		@comment = current_user.comments.new(comment_params)
    	if @comment.save
        	redirect_to comments_path(@comment)
      	end
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def edit
		@comment = Comment.find(params[:id])
		@user = current_user
	end

	def update
		@comment = Comment.find(params[:id])
		@user = current_user
		@comment.update(comment_params)
      redirect_to @comment
	end

	def destroy
		@user = current_user
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to comments_path
	end	

	private
	def comment_params
		params.require(:comment).permit(:user_id, :location, :title, :body)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to new_comment_path, notice: "Logged in!"
  else
    flash.now.alert = "Email or password is invalid"
    render "new"
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 	def index

  end  

  def show
      @user = current_user
      @comment = @user.comments
  end

	def new
  		@user = User.new
	end

	def create
  		@user = User.new(user_params)
  		if @user.save
    	session[:user_id] = @user.id
    	redirect_to new_comment_path, notice: "Thank you for signing up!"
  		else
    	render "new"
  		end
	end 

  def destroy
    User.find(session[:user_id]).destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  def edit
    @user = current_user
  end  

  def update
      @user = current_user
      @user.update(user_params)
      redirect_to @user
  end  

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_index.html.erb
 <div class="box">
	 <% @comment.each do |w| %>
	    <tr>
	      <td>Location:<%= w.location %></td>		
	      <td>Title:<%= w.title %></td>
	      <td>Body:<%= w.body %></td><br>  
	    </tr>
	  <% end %>
 </div> 

app/views/comments/edit.html.erb
	<%= bootstrap_form_for @comment do |c| %>
	<h3>Edit Comment</h3>
	  <%= c.text_field :location %>
	  <%= c.text_field :title %>
	  <%= c.text_area :body %>
	  <%= c.submit ("Submit") %>
	<% end %>

app/views/comments/index.html.erb
    <% if current_user %>
      Logged in as: <%= current_user.email %><br>
     <%= link_to "Log Out", log_out_path %>
    <% else %>
     <%= link_to "Log In", log_in_path %>
    <% end %>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">GoChat</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/comments/new">New Comment</a></li>
      <li class="active"><a href="/comments">View Comments</a></li>
      <li><a href="/users/<%= current_user.id %>/">Profile</a></li>
    </ul>
  </div>
</nav>

<%= render partial: '/comments/index/' %>

app/views/comments/new.html.erb
    <% if current_user %>
      Logged in as: <%= current_user.email %><br>
     <%= link_to "Log Out", log_out_path %>
    <% else %>
     <%= link_to "Log In", log_in_path %>
    <% end %>



<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">GoChat</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/comments/new" class="btn btn-primary" role="button">New Comment</a></li>
      <li><a href="/comments">View Comments</a></li>
      <li><a href="/users/<%= current_user.id %>/">Profile</a></li>
    </ul>
  </div>
</nav>
<div id="comments-form">
	<%= bootstrap_form_for(@comment) do |c| %>
	<h3>New Comment</h3>
	  <%= c.text_field :location %>
	  <%= c.text_field :title %>
	  <%= c.text_area :body %>
	  <%= c.submit ("Submit") %>
	<% end %>
</div>	

app/views/comments/show.html.erb
    <% if current_user %>
      Logged in as: <%= current_user.email %><br>
     <%= link_to "Log Out", log_out_path %>
    <% else %>
     <%= link_to "Log In", log_in_path %>
    <% end %>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">GoChat</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/comments/new" class="btn btn-primary" role="button">New Comment</a></li>
      <li><a href="/comments">View Comments</a></li>
      <li><a href="/users/<%= current_user.id %>/">Profile</a></li>
    </ul>
  </div>
</nav>

<div class="box">
	LOCATION: <%= @comment.location %><br>
	TITLE: <%= @comment.title %><br>
	BODY: <%= @comment.body %><br>
	      <%= link_to 'Edit', edit_comment_path %>
	      <%= link_to 'Destroy', comment_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>              

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- Latest compiled and minified CSS -->



  

    
  </head>

  <body>

    <%= yield %>



  </body>
</html>

app/views/users/edit.html.erb
<!--   <div class="field">
    <%= text_field :email, placeholder: 'email' %>
  </div>
  <div class="field">
    <%= password_field :password, placeholder: 'password' %>
  </div>
  <div class="field">
    <%= password_field :password_confirmation, placeholder: 'password' %>
  </div> -->

    <%= bootstrap_form_for @user do |c| %>
  <h3>Edit User</h3>
    <%= c.text_field :email %>
    <%= c.text_field :password %>
    <%= c.text_area :password_confirmation %>
    <%= c.submit ("Submit") %>
  <% end %>

      <% if current_user %>
      Logged in as: <%= current_user.email %><br>
     <%= link_to "Log Out", log_out_path %>
    <% else %>
     <%= link_to "Log In", log_in_path %>
    <% end %>

app/views/users/new.html.erb
<br><br>
<%= bootstrap_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h3>Sign Up</h3>
  <div class="field">
    <%= f.text_field :email, placeholder: 'email' %>
  </div>
  <div class="field">
    <%= f.password_field :password, placeholder: 'password' %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, placeholder: 'password' %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
      <% if current_user %>
      Logged in as: <%= current_user.email %><br>
     <%= link_to "Log Out", log_out_path %>
    <% else %>
     <%= link_to "Log In", log_in_path %>
    <% end %>
<% end %>

app/views/users/show.html.erb
    <% if current_user %>
      Logged in as: <%= current_user.email %><br>
     <%= link_to "Log Out", log_out_path %>
    <% else %>
     <%= link_to "Log In", log_in_path %>
    <% end %>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">GoChat</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/comments/new">New Comment</a></li>
      <li><a href="/comments">View Comments</a></li>
      <li class="active"><a href="/users/<%= current_user.id %>/">Profile</a></li>
    </ul>
  </div>
</nav>
 <div class="box">
<p>
  Oomail:
  <%= @user.email %>
</p>
 
<p>
  Password:
  <%= @user.password %>
</p>
<%= link_to 'Edit', edit_user_path %>
<%= link_to 'Destroy', user_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %><br>


	 <% @user.comments.each do |w| %>
	      <a href="/comments/<%= w.id %>"><%= w.location %> <%= w.title %> <%= w.body %></a><br>	  
	  <% end %>
 </div> 

app/views/welcome/index.html.erb
<h1>Go Chat</h1>

<body background="africa-15428_1280.jpg">

<% if current_user %>

<div id="landing">
  <a href="/comments/new" class="btn btn-primary" role="button">New Comment</a>
  <br><br>
  <a href="/comments" class="btn btn-primary" role="button">View Comments</a>
  <br><br>
  <a href="/users/<%= current_user.id %>/" class="btn btn-primary" role="button">Profile</a>
</div>  

<% else %>
  <%= render template: "sessions/new" %>
<% end %>

</body>